services:
  backend:
    build:
      context: ./backend # backend 폴더의 Dockerfile 사용
      dockerfile: Dockerfile
    container_name: barimate-backend-dev
    ports:
      - "8000:8000" # 호스트 8000번 -> 컨테이너 8000번
    volumes:
      - ./backend:/app # 로컬 backend 폴더를 컨테이너 /app 에 마운트 (코드 변경 실시간 반영)
    environment:
      # 필요한 환경 변수 (예: API_KEY, FIREBASE_SERVICE_ACCOUNT_KEY_PATH 등)는 여기에 추가하거나 .env 파일 사용
      - WATCHFILES_FORCE_POLLING=true # Docker 볼륨 마운트 환경에서 uvicorn --reload 안정성 향상 (필요시)
      # - PYTHONUNBUFFERED=1 # 이미 Dockerfile에 있지만 명시적으로 추가 가능
    # depends_on: # db 서비스가 없으므로 삭제

  frontend:
    build:
      context: ./frontend # frontend 폴더의 Dockerfile 사용
      dockerfile: Dockerfile
      # target: builder # Dockerfile이 단일 스테이지이므로 이 라인 주석 처리 또는 삭제
      # args: # VITE_API_BASE_URL은 environment로 전달하므로 이 섹션 주석 처리 또는 삭제
      #   - VITE_API_BASE_URL=/api 
    container_name: barimate-frontend-dev
    ports:
      - "5173:5173" # Vite 개발 서버 포트로 변경 (기존 3000:80)
    volumes:
      - ./frontend:/app # 로컬 frontend 폴더를 컨테이너 /app 에 마운트 (소스코드 실시간 반영)
      - /app/node_modules # 컨테이너 내 node_modules를 로컬로 덮어쓰지 않도록 익명 볼륨 사용
    # command: npm run dev # Dockerfile의 CMD를 사용하므로 이 라인 주석 처리 또는 삭제
    depends_on:
      - backend # 백엔드가 먼저 실행되도록 (API 요청을 위해)
    environment:
      - VITE_API_BASE_URL=/api # Vite 개발 서버가 환경 변수를 읽도록 명시
      # CHOKIDAR_USEPOLLING=true # 파일 변경 감지 문제 발생 시 고려

# volumes: # db_data 볼륨 정의 삭제 